# Generated by Django 6.0.7 on 2026-07-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_designer_web_login_designer_web_password_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Токен бота Max')),
                ('bot_username', models.CharField(blank=True, default='', max_length=128, verbose_name='Username бота')),
                ('long_poll_enabled', models.BooleanField(default=True, verbose_name='Long Poll включён')),
                ('updates_marker', models.BigIntegerField(blank=True, null=True, verbose_name='Marker /updates')),
                ('welcome_text', models.TextField(blank=True, default='Здравствуйте! Для регистрации дизайнера отправьте точно:\nРегистрация: Дизайнер', verbose_name='Приветствие')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки Max-бота',
                'verbose_name_plural': 'Настройки Max-бота',
            },
        ),
    ]
