# Generated by Django 6.0.7 on 2026-07-17 07:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Цена')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('done', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус')),
                ('device_type', models.CharField(choices=[('ПК', 'ПК'), ('Ноутбук', 'Ноутбук'), ('Телефон', 'Телефон'), ('Телевизор', 'Телевизор')], default='ПК', max_length=32, verbose_name='Устройство')),
                ('extra_periphery', models.TextField(blank=True, default='', verbose_name='Доп. периферия')),
                ('technical_notes', models.TextField(blank=True, default='', verbose_name='Техническая информация')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Скидка %')),
                ('subtotal_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма до скидки')),
                ('total_sum', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Итого')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='workshop.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ-наряд',
                'verbose_name_plural': 'Заказ-наряды',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AcceptanceAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_number', models.CharField(max_length=32, unique=True, verbose_name='Номер акта')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата приёма')),
                ('device_type', models.CharField(choices=[('ПК', 'ПК'), ('Ноутбук', 'Ноутбук'), ('Телефон', 'Телефон'), ('Телевизор', 'Телевизор')], default='ПК', max_length=32, verbose_name='Тип устройства')),
                ('brand_model', models.CharField(blank=True, default='', max_length=255, verbose_name='Марка / модель')),
                ('serial_number', models.CharField(blank=True, default='', max_length=120, verbose_name='Серийный номер')),
                ('accessories', models.TextField(blank=True, default='', help_text='Зарядка, сумка, мышь и т.д.', verbose_name='Комплектация')),
                ('appearance', models.TextField(blank=True, default='', verbose_name='Внешний вид / повреждения')),
                ('declared_defect', models.TextField(verbose_name='Заявленная неисправность')),
                ('password_info', models.CharField(blank=True, default='', max_length=255, verbose_name='Пароль / PIN')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Примечания')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptance_acts', to='workshop.client', verbose_name='Клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acceptance_acts', to='workshop.order', verbose_name='Связанный заказ')),
            ],
            options={
                'verbose_name': 'Акт приёма-передачи',
                'verbose_name_plural': 'Акты приёма-передачи',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='Название (снимок)')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='workshop.order', verbose_name='Заказ')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='workshop.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Строка заказа',
                'verbose_name_plural': 'Строки заказа',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='workshop.servicecategory', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Категория услуг',
                'verbose_name_plural': 'Категории услуг',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='workshop.servicecategory', verbose_name='Категория'),
        ),
        migrations.AddConstraint(
            model_name='servicecategory',
            constraint=models.UniqueConstraint(fields=('name', 'parent'), name='uniq_category_name_per_parent'),
        ),
    ]
