# Generated by Django 6.0.7 on 2026-07-17 09:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='Пользователь')),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('entity_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Сущность')),
                ('entity_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID сущности')),
                ('details', models.TextField(blank=True, default='', verbose_name='Детали')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Запись журнала',
                'verbose_name_plural': 'Журнал действий',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='mytax_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата чека Мой налог'),
        ),
        migrations.AddField(
            model_name='order',
            name='mytax_issued',
            field=models.BooleanField(default=False, verbose_name='Чек Мой налог выдан'),
        ),
        migrations.AddField(
            model_name='order',
            name='mytax_receipt',
            field=models.FileField(blank=True, null=True, upload_to='mytax_receipts/%Y/%m/', verbose_name='Скриншот чека Мой налог'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('cash', 'Наличные'), ('transfer', 'Перевод (чек)')], default='unpaid', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий к оплате'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='Скриншот чека (перевод)'),
        ),
    ]
