# Generated by Django 6.0.7 on 2026-07-17 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auditlog_order_mytax_at_order_mytax_issued_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Создано')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начато')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('printing', 'Печатается'), ('done', 'Готово'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('file_path', models.CharField(max_length=500, verbose_name='Файл')),
                ('title', models.CharField(max_length=255, verbose_name='Документ')),
                ('doc_type', models.CharField(blank=True, default='', max_length=32, verbose_name='Тип')),
                ('entity_type', models.CharField(blank=True, default='', max_length=64, verbose_name='Сущность')),
                ('entity_id', models.CharField(blank=True, default='', max_length=64, verbose_name='ID сущности')),
                ('copy_index', models.PositiveSmallIntegerField(default=1, verbose_name='Экземпляр')),
                ('copies_total', models.PositiveSmallIntegerField(default=2, verbose_name='Всего экз.')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='Пользователь')),
                ('error', models.TextField(blank=True, default='', verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Задание печати',
                'verbose_name_plural': 'Очередь печати',
                'ordering': ['id'],
            },
        ),
    ]
