# Generated by Django 6.0.7 on 2026-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_printjob_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'В работе'), ('done', 'Завершён'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
