# Generated by Django 6.0.7 on 2026-07-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0004_order_status_in_progress_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Закрыт'),
        ),
    ]
