# Generated by Django 6.0.7 on 2026-07-17 11:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0006_backfill_closed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='SMS включены')),
                ('provider', models.CharField(choices=[('log', 'Только журнал (тест)'), ('smsru', 'SMS.ru')], default='log', max_length=20, verbose_name='Провайдер')),
                ('api_id', models.CharField(blank=True, default='', max_length=255, verbose_name='API ID / ключ')),
                ('sender', models.CharField(blank=True, default='', max_length=32, verbose_name='Имя отправителя')),
                ('debt_template', models.TextField(default='{name}, по заказ-наряду {order} задолженность {sum} руб. Просим оплатить. {company}, {company_phone}', help_text='Плейсхолдеры: {name} {phone} {order} {sum} {company} {company_phone}', verbose_name='Шаблон SMS о долге')),
                ('marketing_enabled', models.BooleanField(default=False, verbose_name='Маркетинг SMS включён')),
                ('marketing_default_text', models.TextField(blank=True, default='Здравствуйте, {name}! Спецпредложение от {company}. Тел. {company_phone}', help_text='Плейсхолдеры: {name} {phone} {company} {company_phone}', verbose_name='Текст маркетинга по умолчанию')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки SMS',
                'verbose_name_plural': 'Настройки SMS',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='allow_marketing_sms',
            field=models.BooleanField(default=True, verbose_name='Можно слать рекламу SMS'),
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда')),
                ('kind', models.CharField(choices=[('debt', 'Долг'), ('marketing', 'Маркетинг'), ('test', 'Тест')], default='debt', max_length=20, verbose_name='Тип')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('text', models.TextField(verbose_name='Текст')),
                ('success', models.BooleanField(default=False, verbose_name='Успех')),
                ('provider', models.CharField(blank=True, default='', max_length=20, verbose_name='Провайдер')),
                ('response', models.TextField(blank=True, default='', verbose_name='Ответ/ошибка')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='Кто отправил')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='workshop.client', verbose_name='Клиент')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='workshop.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'SMS лог',
                'verbose_name_plural': 'SMS логи',
                'ordering': ['-id'],
            },
        ),
    ]
