# Generated by Django 6.0.7 on 2026-07-17 12:40

from django.db import migrations, models


def migrate_smsru_provider(apps, schema_editor):
    SmsSettings = apps.get_model("workshop", "SmsSettings")
    SmsLog = apps.get_model("workshop", "SmsLog")
    SmsSettings.objects.filter(provider="smsru").update(provider="max")
    SmsLog.objects.filter(provider="smsru").update(provider="max")


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0007_sms_settings_and_logs'),
    ]

    operations = [
        migrations.RunPython(migrate_smsru_provider, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='smslog',
            options={'ordering': ['-id'], 'verbose_name': 'Лог сообщений', 'verbose_name_plural': 'Лог сообщений'},
        ),
        migrations.AlterModelOptions(
            name='smssettings',
            options={'verbose_name': 'Настройки Max-рассылок', 'verbose_name_plural': 'Настройки Max-рассылок'},
        ),
        migrations.RemoveField(
            model_name='smssettings',
            name='api_id',
        ),
        migrations.RemoveField(
            model_name='smssettings',
            name='sender',
        ),
        migrations.AddField(
            model_name='client',
            name='max_user_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='ID пользователя в Max после того, как он написал боту', max_length=64, verbose_name='Max user_id'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='bot_link',
            field=models.CharField(blank=True, default='', help_text='Например https://max.ru/your_bot — покажите клиентам для подписки', max_length=255, verbose_name='Ссылка на бота'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='bot_token',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Токен бота Max'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='bot_username',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Username бота'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='long_poll_enabled',
            field=models.BooleanField(default=True, help_text='Фоновый опрос Max API: привязка клиентов по телефону из чата с ботом', verbose_name='Long Poll бота (для LAN без публичного HTTPS)'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='updates_marker',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Маркер long poll'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='welcome_text',
            field=models.TextField(blank=True, default='Здравствуйте! Это бот ИТ-мастерской.\nОтправьте свой номер телефона в формате +79991234567 — привяжем ваш профиль для уведомлений о заказах и долгах.', verbose_name='Приветствие бота'),
        ),
        migrations.AlterField(
            model_name='client',
            name='allow_marketing_sms',
            field=models.BooleanField(default=True, verbose_name='Можно слать маркетинг в Max'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='kind',
            field=models.CharField(choices=[('debt', 'Долг'), ('marketing', 'Маркетинг'), ('test', 'Тест'), ('system', 'Системное')], default='debt', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='Телефон / Max ID'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='provider',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='debt_template',
            field=models.TextField(default='{name}, по заказ-наряду {order} задолженность {sum} руб. Просим оплатить. {company}, {company_phone}', help_text='Плейсхолдеры: {name} {phone} {order} {sum} {company} {company_phone}', verbose_name='Шаблон сообщения о долге'),
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Рассылки включены'),
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='marketing_enabled',
            field=models.BooleanField(default=False, verbose_name='Маркетинг включён'),
        ),
        migrations.AlterField(
            model_name='smssettings',
            name='provider',
            field=models.CharField(choices=[('log', 'Только журнал (тест)'), ('max', 'Max мессенджер')], default='log', max_length=20, verbose_name='Канал'),
        ),
    ]
