# Generated by Django 6.0.7 on 2026-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0008_max_messaging_replace_smsru'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptanceact',
            name='client_called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Звонок клиенту'),
        ),
        migrations.AddField(
            model_name='acceptanceact',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Диагностика/работа завершена'),
        ),
        migrations.AddField(
            model_name='acceptanceact',
            name='status',
            field=models.CharField(choices=[('diagnostics', 'Диагностика идёт'), ('diagnostics_done', 'Диагностика выполнена'), ('done', 'Выполнена')], db_index=True, default='diagnostics', max_length=32, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_called_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Звонок клиенту'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'В работе'), ('ready_call', 'Работа выполнена — позвонить'), ('done', 'Выполнена'), ('cancelled', 'Отменён')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
