# Generated by Django 6.0.7 on 2026-07-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0009_work_queue_acts_and_call_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='YandexAiSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, verbose_name='Ежедневный AI-отчёт включён')),
                ('api_key', models.CharField(blank=True, default='', max_length=255, verbose_name='API-ключ Yandex Cloud')),
                ('folder_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Folder ID каталога')),
                ('model_name', models.CharField(blank=True, default='yandexgpt-lite', help_text='Например yandexgpt-lite или yandexgpt', max_length=64, verbose_name='Модель')),
                ('admin_phone', models.CharField(blank=True, default='', help_text='Клиент с этим телефоном должен быть привязан к Max', max_length=32, verbose_name='Телефон администратора')),
                ('admin_max_user_id', models.CharField(blank=True, default='', help_text='Можно указать напрямую, если телефон ещё не привязан', max_length=64, verbose_name='Max user_id администратора')),
                ('report_hour_msk', models.PositiveSmallIntegerField(default=20, help_text='Отчёт уходит в начале этого часа по Москве', verbose_name='Час отправки (МСК)')),
                ('last_report_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего отчёта')),
                ('last_report_at', models.DateTimeField(blank=True, null=True, verbose_name='Когда отправляли')),
                ('last_report_text', models.TextField(blank=True, default='', verbose_name='Текст последнего отчёта')),
                ('last_report_error', models.TextField(blank=True, default='', verbose_name='Ошибка последней отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки Яндекс ИИ',
                'verbose_name_plural': 'Настройки Яндекс ИИ',
            },
        ),
    ]
