# Generated by Django 6.0.7 on 2026-07-19 10:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0010_yandex_ai_daily_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='discount_manual',
            field=models.BooleanField(default=False, help_text='Если включено — авто-скидка 10% за постоянство не перезаписывает значение', verbose_name='Скидка задана вручную'),
        ),
        migrations.AddField(
            model_name='client',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ручная скидка клиента 0–15%. С 3-го заказа автоматически ставится 10%.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)], verbose_name='Скидка %'),
        ),
    ]
