# Generated by Django 6.0.7 on 2026-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0012_backfill_regular_client_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='smssettings',
            name='diagnostics_done_template',
            field=models.TextField(default='{name}, диагностика по акту {act} выполнена. Устройство: {device}. {company}, {company_phone}', help_text='Плейсхолдеры: {name} {phone} {act} {device} {company} {company_phone}', verbose_name='Шаблон: диагностика выполнена'),
        ),
        migrations.AddField(
            model_name='smssettings',
            name='order_done_template',
            field=models.TextField(default='{name}, заказ-наряд {order} выполнен. Сумма: {sum} руб. Ждём вас. {company}, {company_phone}', help_text='Плейсхолдеры: {name} {phone} {order} {sum} {company} {company_phone}', verbose_name='Шаблон: заказ выполнен'),
        ),
    ]
