# Generated by Django 6.0.7 on 2026-07-20 10:12

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0015_ai_report_minute'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubConnectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер точки')),
                ('hub_base_url', models.CharField(blank=True, default='', max_length=255, verbose_name='URL хаба')),
                ('site_token', models.CharField(blank=True, default='', max_length=255, verbose_name='Token точки')),
                ('site_secret', models.CharField(blank=True, default='', max_length=255, verbose_name='Secret HMAC')),
                ('designer_share_percent', models.PositiveSmallIntegerField(default=70, help_text='От agreed_price; остаток — доля точки', verbose_name='Доля дизайнера %')),
                ('enabled', models.BooleanField(default=False, verbose_name='Интеграция с хабом включена')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки HUB',
                'verbose_name_plural': 'Настройки HUB',
            },
        ),
        migrations.CreateModel(
            name='HubWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('payload', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='StaffUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(max_length=128, verbose_name='Хэш пароля')),
                ('full_name', models.CharField(blank=True, default='', max_length=200, verbose_name='ФИО')),
                ('role', models.CharField(choices=[('admin', 'Админ'), ('manager', 'Менеджер')], default='manager', max_length=20, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('max_user_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Max user_id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='ModelingBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_number', models.CharField(max_length=32, unique=True, verbose_name='Номер')),
                ('model_url', models.URLField(blank=True, default='', verbose_name='Ссылка на модель')),
                ('stl_file', models.FileField(blank=True, upload_to='modeling/stl/%Y/%m/', verbose_name='STL')),
                ('description', models.TextField(blank=True, default='', verbose_name='ТЗ / комментарий')),
                ('agreed_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма с клиентом')),
                ('designer_share_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Доля дизайнера')),
                ('site_share_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Доля точки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('queued', 'В очереди'), ('assigned', 'Назначен'), ('in_progress', 'В работе'), ('needs_clarification', 'Переуточнение'), ('clarification_provided', 'Уточнение отправлено'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=32, verbose_name='Статус')),
                ('hub_brief_id', models.CharField(blank=True, db_index=True, default='', max_length=64, verbose_name='ID на хабе')),
                ('designer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Дизайнер ФИО')),
                ('designer_id', models.CharField(blank=True, default='', max_length=64, verbose_name='Дизайнер ID')),
                ('eta', models.CharField(blank=True, default='', max_length=200, verbose_name='Ориентировочный срок')),
                ('last_hub_message', models.TextField(blank=True, default='', verbose_name='Последнее сообщение с хаба')),
                ('manager_alert', models.BooleanField(db_index=True, default=False, verbose_name='Нужно внимание менеджера')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modeling_briefs', to='workshop.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_briefs', to='workshop.staffuser', verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_briefs', to='workshop.staffuser', verbose_name='Изменил')),
            ],
            options={
                'verbose_name': '3D заявка',
                'verbose_name_plural': '3D заявки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ModelingBriefScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='modeling/screens/%Y/%m/', verbose_name='Скриншот')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='workshop.modelingbrief')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
