# Generated by Django 6.0.7 on 2026-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0016_staff_and_modeling_briefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelingbrief',
            name='delivery_address',
            field=models.TextField(blank=True, default='', help_text='Только для мастерской; в HUB не отправляется', verbose_name='Адрес доставки напечатанной модели'),
        ),
    ]
