# Generated by Django 6.0.7 on 2026-07-21 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0017_modeling_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='additive_service_type',
            field=models.CharField(blank=True, choices=[('3D сканирование', '3D сканирование'), ('3D печать', '3D печать'), ('3D моделирование', '3D моделирование')], default='', max_length=32, verbose_name='Тип аддитивной услуги'),
        ),
        migrations.AddField(
            model_name='order',
            name='additive_services_enabled',
            field=models.BooleanField(default=False, verbose_name='Аддитивные услуги'),
        ),
        migrations.AlterField(
            model_name='acceptanceact',
            name='device_type',
            field=models.CharField(choices=[('ПК', 'ПК'), ('Ноутбук', 'Ноутбук'), ('Телефон', 'Телефон'), ('Планшет', 'Планшет'), ('Телевизор', 'Телевизор')], default='ПК', max_length=32, verbose_name='Тип устройства'),
        ),
        migrations.AlterField(
            model_name='order',
            name='device_type',
            field=models.CharField(choices=[('ПК', 'ПК'), ('Ноутбук', 'Ноутбук'), ('Телефон', 'Телефон'), ('Планшет', 'Планшет'), ('Телевизор', 'Телевизор')], default='ПК', max_length=32, verbose_name='Устройство'),
        ),
    ]
