# Generated by Django 6.0.7 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0019_modeling_brief_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smssettings',
            name='order_done_template',
            field=models.TextField(default='{name}, заказ-наряд {order} выполнен. Сумма: {sum} руб. Ждём вас. {company}, {company_phone}', help_text='Уходит в Max при статусе «Работа выполнена — позвонить», только если у клиента есть Max user_id. Плейсхолдеры: {name} {phone} {order} {sum} {company} {company_phone}', verbose_name='Шаблон: заказ выполнен'),
        ),
    ]
