# Generated by Django 6.0.7 on 2026-07-30 12:25

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0020_model_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smslog',
            name='kind',
            field=models.CharField(choices=[('debt', 'Долг'), ('marketing', 'Маркетинговое'), ('order', 'Заказ'), ('test', 'Тест'), ('system', 'Системное')], default='debt', max_length=20, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='SoftwareDevContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=32, unique=True, verbose_name='Номер договора')),
                ('kind', models.CharField(choices=[('chatbot', 'Разработка чат-бота')], db_index=True, default='chatbot', max_length=32, verbose_name='Вид разработки')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'В работе'), ('ready', 'Готово к сдаче'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=32, verbose_name='Статус')),
                ('product_name', models.TextField(blank=True, default='', help_text='Предмет договора (п. 1.1)', verbose_name='Название программного комплекса')),
                ('description', models.TextField(blank=True, default='', verbose_name='Краткое описание / заметки')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Стоимость работ')),
                ('payment_variant', models.CharField(choices=[('A', 'А: аванс + остаток после акта'), ('B', 'Б: оплата после акта')], default='B', max_length=1, verbose_name='Вариант оплаты')),
                ('prepayment_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Для варианта А', max_digits=12, verbose_name='Сумма аванса')),
                ('prepayment_due', models.DateField(blank=True, null=True, verbose_name='Срок аванса')),
                ('access_days', models.PositiveSmallIntegerField(default=7, help_text='П. 1.5 договора (для чат-бота обычно 7)', verbose_name='Срок доступа (дней)')),
                ('contract_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата договора')),
                ('github_url', models.URLField(blank=True, default='', verbose_name='Ссылка на репозиторий GitHub')),
                ('tz_file', models.FileField(blank=True, upload_to='software/tz/%Y/%m/', verbose_name='ТЗ от клиента (файл)')),
                ('tz_text', models.TextField(blank=True, default='', verbose_name='ТЗ текстом')),
                ('customer_full_name', models.CharField(blank=True, default='', max_length=255, verbose_name='ФИО заказчика')),
                ('customer_passport_series', models.CharField(blank=True, default='', max_length=16, verbose_name='Паспорт серия')),
                ('customer_passport_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Паспорт номер')),
                ('customer_passport_issued', models.CharField(blank=True, default='', max_length=255, verbose_name='Паспорт выдан')),
                ('customer_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адрес регистрации')),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email заказчика')),
                ('customer_inn', models.CharField(blank=True, default='', max_length=20, verbose_name='ИНН заказчика')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='software_contracts', to='workshop.client', verbose_name='Клиент')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_software_contracts', to='workshop.staffuser', verbose_name='Создал')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_software_contracts', to='workshop.staffuser', verbose_name='Изменил')),
            ],
            options={
                'verbose_name': 'Договор заказной разработки',
                'verbose_name_plural': 'Договоры заказной разработки',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareDevComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='Автор')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='workshop.softwaredevcontract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Комментарий по разработке',
                'verbose_name_plural': 'Комментарии по разработке',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareDevPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='software/photos/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, default='', max_length=200, verbose_name='Подпись')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='workshop.softwaredevcontract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Фото к ТЗ',
                'verbose_name_plural': 'Фото к ТЗ',
                'ordering': ['id'],
            },
        ),
    ]
