# Generated by Django 6.0.7 on 2026-07-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0021_software_dev_contracts'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredevcontract',
            name='mytax_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата чека Мой налог'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='mytax_issued',
            field=models.BooleanField(default=False, verbose_name='Чек Мой налог выдан'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='mytax_receipt',
            field=models.FileField(blank=True, null=True, upload_to='software/mytax_receipts/%Y/%m/', verbose_name='Скриншот чека Мой налог'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='payment_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='payment_method',
            field=models.CharField(choices=[('unpaid', 'Не оплачен'), ('cash', 'Наличные'), ('transfer', 'Перевод (чек)')], default='unpaid', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='payment_note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Комментарий к оплате'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='payment_receipt',
            field=models.FileField(blank=True, null=True, upload_to='software/payment_receipts/%Y/%m/', verbose_name='Скриншот чека (перевод)'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='signed_contract_file',
            field=models.FileField(blank=True, help_text='Распечатанный договор с подписью клиента', null=True, upload_to='software/signed/%Y/%m/', verbose_name='Подписанный договор (скан)'),
        ),
    ]
