# Generated by Django 6.0.7 on 2026-07-30 13:04

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0022_software_payment_signed_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='softwaredevcontract',
            name='price_needs_reagree',
            field=models.BooleanField(db_index=True, default=False, help_text='Включается при новой версии ТЗ, пока менеджер не подтвердит новую сумму', verbose_name='Нужно пересогласовать цену'),
        ),
        migrations.AddField(
            model_name='softwaredevcontract',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='Версия договора'),
        ),
        migrations.AlterField(
            model_name='softwaredevcontract',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending_signature', 'На подписании у клиента'), ('in_progress', 'В работе'), ('ready', 'Готово к сдаче'), ('done', 'Выполнен'), ('cancelled', 'Отменён')], db_index=True, default='draft', max_length=32, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='SoftwareDevVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('product_name', models.TextField(blank=True, default='', verbose_name='Название ПО')),
                ('tz_text', models.TextField(blank=True, default='', verbose_name='ТЗ текстом')),
                ('tz_file', models.FileField(blank=True, upload_to='software/tz_versions/%Y/%m/', verbose_name='Файл ТЗ')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Сумма на момент версии')),
                ('note', models.TextField(blank=True, default='', verbose_name='Что изменилось')),
                ('price_agreed', models.BooleanField(default=True, verbose_name='Цена была согласована')),
                ('username', models.CharField(blank=True, default='', max_length=64, verbose_name='Кто зафиксировал')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workshop.softwaredevcontract', verbose_name='Договор')),
            ],
            options={
                'verbose_name': 'Версия договора ПО',
                'verbose_name_plural': 'Версии договора ПО',
                'ordering': ['-version', '-id'],
                'unique_together': {('contract', 'version')},
            },
        ),
    ]
