# Generated by Django 6.0.7 on 2026-08-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0023_software_version_pending_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDisplaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='Агент клиентского экрана')),
                ('mode', models.CharField(choices=[('ads', 'Реклама'), ('mirror', 'Дубль CRM')], db_index=True, default='ads', max_length=16, verbose_name='Режим')),
                ('tv_monitor_key', models.CharField(blank=True, default='', max_length=128, verbose_name='Ключ монитора ТВ')),
                ('crm_monitor_key', models.CharField(blank=True, default='', max_length=128, verbose_name='Ключ монитора CRM')),
                ('tv_left', models.IntegerField(default=0, verbose_name='ТВ left')),
                ('tv_top', models.IntegerField(default=0, verbose_name='ТВ top')),
                ('tv_width', models.PositiveIntegerField(default=1920, verbose_name='ТВ width')),
                ('tv_height', models.PositiveIntegerField(default=1080, verbose_name='ТВ height')),
                ('crm_left', models.IntegerField(default=0, verbose_name='CRM left')),
                ('crm_top', models.IntegerField(default=0, verbose_name='CRM top')),
                ('crm_width', models.PositiveIntegerField(default=1920, verbose_name='CRM width')),
                ('crm_height', models.PositiveIntegerField(default=1080, verbose_name='CRM height')),
                ('monitors_cache', models.JSONField(blank=True, default=list, verbose_name='Кэш списка мониторов')),
                ('chrome_path', models.CharField(blank=True, default='', max_length=512, verbose_name='Путь к Chrome/Edge')),
                ('slide_interval_sec', models.PositiveIntegerField(default=9, verbose_name='Интервал слайдов (сек)')),
                ('last_error', models.CharField(blank=True, default='', max_length=500, verbose_name='Последняя ошибка агента')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Клиентский экран (ТВ)',
                'verbose_name_plural': 'Клиентский экран (ТВ)',
            },
        ),
    ]
